use ndarray::{s, Array2, ArrayView, ArrayViewD, Dim, Dimension, IxDynImpl};

/// Pooling strategy applied to the model's token-level output to produce a
/// single fixed-size embedding per input text.
///
/// `Eq` is intentionally not derived because [`Pooling::PrePooledU8`] contains
/// `f32` which does not implement `Eq`.
#[derive(Debug, Clone, PartialEq)]
pub enum Pooling {
    Cls,
    Mean,
    /// Last-token pooling: takes the embedding at the last non-padding position.
    ///
    /// Required for decoder-style models such as Qwen3-Embedding, where the
    /// final token carries the aggregated sequence representation.
    LastToken,
    /// The model already outputs a pre-pooled 2D tensor stored as `u8`.
    ///
    /// Applies affine dequantization: `f32 = (u8 − zero_point) × scale`.
    /// Used for calibrated uint8 models such as
    /// `electroglyph/Qwen3-Embedding-0.6B-onnx-uint8`.
    PrePooledU8 {
        scale: f32,
        zero_point: u8,
    },
}

impl Default for Pooling {
    /// Change this to define the default pooling strategy.
    ///
    /// Currently this is set to [`Self::Cls`] for backward compatibility.
    fn default() -> Self {
        Self::Cls
    }
}

pub fn cls(tensor: &ArrayView<f32, Dim<IxDynImpl>>) -> anyhow::Result<Array2<f32>> {
    match tensor.dim().ndim() {
        2 => Ok(tensor.slice(s![.., ..]).to_owned()),
        3 => Ok(tensor.slice(s![.., 0, ..]).to_owned()),
        _ => Err(anyhow::Error::msg(format!(
            "Invalid output shape: {shape:?}. Expected 2D or 3D tensor.",
            shape = tensor.dim()
        ))),
    }
}

/// Pool by selecting the last non-padding token embedding per sample.
///
/// `attention_mask_array` must have shape `[batch, seq]` with 1 for real tokens
/// and 0 for padding; the index of the last 1 is used as the token position.
pub fn last_token(
    token_embeddings: &ArrayView<f32, Dim<IxDynImpl>>,
    attention_mask_array: Array2<i64>,
) -> anyhow::Result<Array2<f32>> {
    if token_embeddings.dim().ndim() == 2 {
        return Ok(token_embeddings.slice(s![.., ..]).to_owned());
    } else if token_embeddings.dim().ndim() != 3 {
        return Err(anyhow::Error::msg(format!(
            "Invalid output shape: {shape:?}. Expected 2D or 3D tensor.",
            shape = token_embeddings.dim()
        )));
    }

    let batch_size = token_embeddings.shape()[0];
    let hidden_size = token_embeddings.shape()[2];
    let mut result = Array2::zeros((batch_size, hidden_size));

    for i in 0..batch_size {
        let mask_sum = attention_mask_array
            .row(i)
            .iter()
            .filter(|&&v| v > 0)
            .count();
        let last_pos = if mask_sum > 0 { mask_sum - 1 } else { 0 };
        result
            .row_mut(i)
            .assign(&token_embeddings.slice(s![i, last_pos, ..]));
    }

    Ok(result)
}

/// Dequantize a pre-pooled uint8 tensor using affine dequantization.
///
/// `f32 = (u8 − zero_point) × scale`
///
/// The input tensor must be 2D `[batch, dim]` — the model has already performed
/// pooling internally and stored the result as calibrated uint8 values.
pub fn dequant_u8(
    tensor: &ArrayViewD<u8>,
    scale: f32,
    zero_point: u8,
) -> anyhow::Result<Array2<f32>> {
    match tensor.ndim() {
        2 => {
            let shape = tensor.shape();
            let (batch, dim) = (shape[0], shape[1]);
            let mut result = Array2::zeros((batch, dim));
            for (i, row) in tensor.outer_iter().enumerate() {
                for (j, &v) in row.iter().enumerate() {
                    result[[i, j]] = (v as f32 - zero_point as f32) * scale;
                }
            }
            Ok(result)
        }
        _ => Err(anyhow::Error::msg(format!(
            "dequant_u8: expected 2D tensor [batch, dim], got shape {:?}",
            tensor.shape()
        ))),
    }
}

/// Pool the previous layer output by taking the element-wise arithmetic mean of the token-level embeddings after applying the attention mask.
///
/// * `token_embeddings` - token embeddings in form of a tensor output of the encoding.
/// * `attention_mask_array` - is the same mask generated by Tokenizer and used for encoding.
// Please refer to the original python implementation for more details:
// https://github.com/UKPLab/sentence-transformers/blob/c0fc0e8238f7f48a1e92dc90f6f96c86f69f1e02/sentence_transformers/models/Pooling.py#L151
pub fn mean(
    token_embeddings: &ArrayView<f32, Dim<IxDynImpl>>,
    attention_mask_array: Array2<i64>,
) -> anyhow::Result<Array2<f32>> {
    let attention_mask_original_dim = attention_mask_array.dim();

    if token_embeddings.dim().ndim() == 2 {
        // There are no means to speak of if the Axis(1) is missing.
        // Typically we'll see a dimension of (batch_size, feature_count) here.
        // It can be assumed that pooling is already done within the model.
        return Ok(token_embeddings.slice(s![.., ..]).to_owned());
    } else if token_embeddings.dim().ndim() != 3 {
        return Err(anyhow::Error::msg(format!(
            "Invalid output shape: {shape:?}. Expected 2D or 3D tensor.",
            shape = token_embeddings.dim()
        )));
    }

    let token_embeddings =
        // If the token_embeddings is 3D, return the whole thing.
        // Using `slice` here to assert the dimension.
        token_embeddings
            .slice(s![.., .., ..]);

    // Compute attention mask
    let attention_mask = attention_mask_array
        .insert_axis(ndarray::Axis(2))
        .broadcast(token_embeddings.dim())
        .ok_or_else(|| {
            anyhow::Error::msg(format!(
                "Could not broadcast attention mask from {:?} to {:?}",
                attention_mask_original_dim,
                token_embeddings.dim()
            ))
        })?
        .mapv(|x| x as f32);

    let masked_tensor = &attention_mask * &token_embeddings;
    let sum = masked_tensor.sum_axis(ndarray::Axis(1));
    let mask_sum = attention_mask.sum_axis(ndarray::Axis(1));
    let mask_sum = mask_sum.mapv(|x| if x == 0f32 { 1.0 } else { x });
    Ok(&sum / &mask_sum)
}
